services:
  postgres:
    image: postgres:15
    container_name: reservation-service-db
    environment:
      POSTGRES_DB: reservation_service_db
    env_file:
      - src/main/resources/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata-reservation-service-store:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata-reservation-service-store:
